version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    networks:
      - jenkins-net
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      - jenkins-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - jenkins

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    networks:
      - jenkins-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TEST_USER: ${TEST_USER}
      TEST_PASSWORD: ${TEST_PASSWORD}
      LARAVEL_PGSQL_TEST_DB: ${LARAVEL_PGSQL_TEST_DB}
      CAKE_PGSQL_TEST_DB: ${CAKE_PGSQL_TEST_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-postgres-dbs.sh:/docker-entrypoint-initdb.d/init-postgres-dbs.sh
    ports:
      - "127.0.0.1:5432:5432"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    networks:
      - jenkins-net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TEST_USER: ${TEST_USER}
      TEST_PASSWORD: ${TEST_PASSWORD}
      LARAVEL_MYSQL_TEST_DB: ${LARAVEL_MYSQL_TEST_DB}
      CAKE_MYSQL_TEST_DB: ${CAKE_MYSQL_TEST_DB}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-mysql-dbs.sh:/docker-entrypoint-initdb.d/init-mysql-dbs.sh
    ports:
      - "127.0.0.1:3306:3306"

  php-test:
    build: 
      context: ./php-test
      dockerfile: Dockerfile
    container_name: php-test
    networks:
      - jenkins-net
    environment:
      TEST_USER: ${TEST_USER}
      TEST_PASSWORD: ${TEST_PASSWORD}
      LARAVEL_MYSQL_TEST_DB: ${LARAVEL_MYSQL_TEST_DB}
      CAKE_MYSQL_TEST_DB: ${CAKE_MYSQL_TEST_DB}
      LARAVEL_PGSQL_TEST_DB: ${LARAVEL_PGSQL_TEST_DB}
      CAKE_PGSQL_TEST_DB: ${CAKE_PGSQL_TEST_DB}
    volumes:
      - ./php-test/tests:/app/tests

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins-data:
    name: jenkins-data
  postgres-data:
    name: postgres-data
  mysql-data:
    name: mysql-data
