#!/bin/bash
set -e

# Create test databases
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_TEST_USER WITH PASSWORD '$POSTGRES_TEST_PASSWORD';
    CREATE DATABASE $POSTGRES_CAKE_TEST_DB;
    CREATE DATABASE $POSTGRES_LARAVEL_TEST_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_CAKE_TEST_DB TO $POSTGRES_TEST_USER;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_LARAVEL_TEST_DB TO $POSTGRES_TEST_USER;
EOSQL
