#!/bin/bash
set -e

mysql -u root -p$MYSQL_ROOT_PASSWORD <<-EOSQL
    CREATE DATABASE IF NOT EXISTS ${MYSQL_CAKE_TEST_DB};
    CREATE DATABASE IF NOT EXISTS ${MYSQL_LARAVEL_TEST_DB};
    CREATE USER IF NOT EXISTS '$DB_TEST_USER'@'%' IDENTIFIED BY '$DB_TEST_PASSWORD';
    GRANT ALL PRIVILEGES ON ${MYSQL_CAKE_TEST_DB}.* TO '$DB_TEST_USER'@'%';
    GRANT ALL PRIVILEGES ON ${MYSQL_LARAVEL_TEST_DB}.* TO '$DB_TEST_USER'@'%';
    FLUSH PRIVILEGES;
EOSQL
